### ISSUE TITLE
HandlePlanning.py - Probably hitting a bug for times between 23:30 and 0:00

### ISSUE THREAD

**Issue by gbraux** [SixK/CC1101-X2D-Heaters#1]
Hi,

When current time is between 23.30 & 0.00, the PyDeltia Cron Task is crashing ...

Traceback (most recent call last):
  File "/home/osmc/Conde_Home_Automation/presence_automation.py", line 464, in <module>
    heater_control.UpdateHeatersStates()
  File "/home/osmc/Conde_Home_Automation/heater_control.py", line 55, in UpdateHeatersStates
    stat1=stateNames[zone1.getStatus(dayName, timeStr)]
  File "/home/osmc/Conde_Home_Automation/HandlePlanning.py", line 59, in getStatus
    hPos=self.getTimeHoraire(time)
  File "/home/osmc/Conde_Home_Automation/HandlePlanning.py", line 50, in getTimeHoraire
    if horaire <= time and self._horaireList[x+1] >time :
IndexError: list index out of range

Guillaume.

**Comment by SixK** [comment]
Hi,

Thank's for this issue report
It's fixed, LibreOffice was converting 24:00:00 to 00:00:00
I simply changed last hour format from Time to Text in chauffage.ods

SixK
